// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/analisis/lexico.jflex

package analisis;

//importaciones
import java_cup.runtime.Symbol;
import java.util.LinkedList;
import Excepciones.Errores;


@SuppressWarnings("fallthrough")
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  1,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  4,  5,  0,  0,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 19, 20, 21, 22,  0, 
     0, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 
    38, 32, 39, 40, 41, 42, 43, 44, 32, 32, 32, 45, 46, 47, 48, 49, 
    50, 23, 24, 25, 26, 27, 51, 29, 30, 31, 32, 33, 34, 35, 52, 37, 
    38, 32, 53, 40, 54, 55, 43, 44, 32, 32, 32, 56, 57, 58,  0,  0, 
     0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\16\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\1\1\30\1\31\1\0\1\32\1\33"+
    "\2\0\1\34\1\0\1\2\1\0\1\35\1\36\1\37"+
    "\4\22\1\40\3\22\1\41\11\22\1\42\1\43\2\0"+
    "\1\44\7\22\1\45\1\46\6\22\1\47\2\22\1\0"+
    "\1\2\1\50\1\22\1\51\3\22\1\52\6\22\1\53"+
    "\1\54\1\22\1\0\1\55\1\56\2\22\1\57\1\60"+
    "\4\22\1\61\1\0\1\22\1\62\1\22\1\63\1\22"+
    "\1\64\1\22\1\65\1\22\1\66\2\22\1\67";

  private static int [] zzUnpackAction() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\73\0\u0127\0\u0162"+
    "\0\73\0\73\0\u019d\0\73\0\73\0\73\0\u01d8\0\u0213"+
    "\0\73\0\73\0\u024e\0\u0289\0\u02c4\0\u02ff\0\u033a\0\u0375"+
    "\0\u03b0\0\u03eb\0\u0426\0\u0461\0\u049c\0\u04d7\0\u0512\0\u054d"+
    "\0\u0588\0\u05c3\0\u05fe\0\u02ff\0\u02ff\0\u02ff\0\u02ff\0\73"+
    "\0\u0639\0\73\0\73\0\354\0\73\0\73\0\u0674\0\u06af"+
    "\0\73\0\u06ea\0\u0725\0\u0760\0\73\0\73\0\73\0\u079b"+
    "\0\u07d6\0\u0811\0\u084c\0\u0887\0\u08c2\0\u08fd\0\u0938\0\u02ff"+
    "\0\u0973\0\u09ae\0\u09e9\0\u0a24\0\u0a5f\0\u0a9a\0\u0ad5\0\u0b10"+
    "\0\u0b4b\0\73\0\73\0\u0b86\0\u0bc1\0\u0760\0\u0bfc\0\u0c37"+
    "\0\u0c72\0\u0cad\0\u0ce8\0\u0d23\0\u0d5e\0\u02ff\0\u02ff\0\u0d99"+
    "\0\u0dd4\0\u0e0f\0\u0e4a\0\u0e85\0\u0ec0\0\u02ff\0\u0efb\0\u0f36"+
    "\0\u0f71\0\73\0\u02ff\0\u0fac\0\u02ff\0\u0fe7\0\u1022\0\u105d"+
    "\0\u02ff\0\u1098\0\u10d3\0\u110e\0\u1149\0\u1184\0\u11bf\0\u02ff"+
    "\0\u02ff\0\u11fa\0\u1235\0\u02ff\0\u02ff\0\u1270\0\u12ab\0\u02ff"+
    "\0\u02ff\0\u12e6\0\u1321\0\u135c\0\u1397\0\u02ff\0\u13d2\0\u140d"+
    "\0\u02ff\0\u1448\0\u02ff\0\u1483\0\u02ff\0\u14be\0\u02ff\0\u14f9"+
    "\0\u02ff\0\u1534\0\u156f\0\u02ff";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\2\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\2\26\1\34\3\26\1\35"+
    "\2\26\1\36\1\37\1\40\1\41\1\26\1\42\1\43"+
    "\1\44\1\26\1\45\1\46\1\47\1\26\1\33\1\26"+
    "\1\37\1\41\1\26\1\50\1\51\1\52\74\0\2\3"+
    "\115\0\1\53\45\0\5\54\1\55\65\54\7\0\1\56"+
    "\63\0\5\57\1\0\50\57\1\60\14\57\13\0\1\61"+
    "\72\0\1\62\4\0\1\63\71\0\1\64\1\0\1\20"+
    "\76\0\1\65\72\0\1\66\72\0\1\67\66\0\1\26"+
    "\5\0\26\26\4\0\1\26\1\0\5\26\24\0\1\26"+
    "\5\0\16\26\1\70\1\26\1\71\5\26\4\0\1\26"+
    "\1\0\2\26\1\71\2\26\24\0\1\26\5\0\7\26"+
    "\1\72\6\26\1\73\7\26\4\0\1\26\1\0\5\26"+
    "\24\0\1\26\5\0\16\26\1\74\7\26\4\0\1\26"+
    "\1\0\5\26\24\0\1\26\5\0\13\26\1\75\12\26"+
    "\4\0\1\26\1\0\5\26\24\0\1\26\5\0\1\76"+
    "\15\26\1\77\7\26\4\0\1\26\1\0\5\26\24\0"+
    "\1\26\5\0\5\26\1\100\7\26\1\101\10\26\4\0"+
    "\1\26\1\0\1\100\1\101\3\26\24\0\1\26\5\0"+
    "\1\102\25\26\4\0\1\26\1\0\5\26\24\0\1\26"+
    "\5\0\20\26\1\103\5\26\4\0\1\26\1\0\2\26"+
    "\1\103\2\26\24\0\1\26\5\0\4\26\1\104\21\26"+
    "\4\0\1\26\1\0\5\26\24\0\1\26\5\0\22\26"+
    "\1\105\3\26\4\0\1\26\1\0\3\26\1\105\1\26"+
    "\24\0\1\26\5\0\20\26\1\106\5\26\4\0\1\26"+
    "\1\0\2\26\1\106\2\26\24\0\1\26\5\0\1\107"+
    "\15\26\1\110\7\26\4\0\1\26\1\0\5\26\24\0"+
    "\1\26\5\0\7\26\1\111\16\26\4\0\1\26\1\0"+
    "\5\26\74\0\1\112\11\0\1\113\72\0\1\113\52\0"+
    "\4\57\1\114\3\0\13\62\1\115\57\62\2\63\1\0"+
    "\70\63\21\0\1\116\72\0\1\26\5\0\16\26\1\117"+
    "\7\26\4\0\1\26\1\0\5\26\24\0\1\26\5\0"+
    "\4\26\1\120\21\26\4\0\1\26\1\0\5\26\24\0"+
    "\1\26\5\0\1\121\25\26\4\0\1\26\1\0\5\26"+
    "\24\0\1\26\5\0\15\26\1\122\10\26\4\0\1\26"+
    "\1\0\1\26\1\122\3\26\24\0\1\26\5\0\23\26"+
    "\1\123\2\26\4\0\1\26\1\0\4\26\1\123\24\0"+
    "\1\26\5\0\21\26\1\124\4\26\4\0\1\26\1\0"+
    "\5\26\24\0\1\26\5\0\13\26\1\125\12\26\4\0"+
    "\1\26\1\0\5\26\24\0\1\26\5\0\20\26\1\126"+
    "\5\26\4\0\1\26\1\0\2\26\1\126\2\26\24\0"+
    "\1\26\5\0\22\26\1\127\3\26\4\0\1\26\1\0"+
    "\3\26\1\127\1\26\24\0\1\26\5\0\22\26\1\130"+
    "\3\26\4\0\1\26\1\0\3\26\1\130\1\26\24\0"+
    "\1\26\5\0\10\26\1\131\15\26\4\0\1\26\1\0"+
    "\5\26\24\0\1\26\5\0\22\26\1\132\3\26\4\0"+
    "\1\26\1\0\3\26\1\132\1\26\24\0\1\26\5\0"+
    "\1\133\17\26\1\134\5\26\4\0\1\26\1\0\2\26"+
    "\1\134\2\26\24\0\1\26\5\0\23\26\1\135\2\26"+
    "\4\0\1\26\1\0\4\26\1\135\24\0\1\26\5\0"+
    "\20\26\1\136\5\26\4\0\1\26\1\0\2\26\1\136"+
    "\2\26\24\0\1\26\5\0\10\26\1\137\15\26\4\0"+
    "\1\26\1\0\5\26\24\0\1\26\5\0\10\26\1\140"+
    "\15\26\4\0\1\26\1\0\5\26\24\0\1\141\5\0"+
    "\6\141\26\0\1\141\7\0\13\62\1\115\4\62\1\142"+
    "\52\62\21\0\1\26\5\0\13\26\1\143\12\26\4\0"+
    "\1\26\1\0\5\26\24\0\1\26\5\0\1\144\25\26"+
    "\4\0\1\26\1\0\5\26\24\0\1\26\5\0\20\26"+
    "\1\145\5\26\4\0\1\26\1\0\2\26\1\145\2\26"+
    "\24\0\1\26\5\0\21\26\1\146\1\147\3\26\4\0"+
    "\1\26\1\0\3\26\1\147\1\26\24\0\1\26\5\0"+
    "\1\26\1\150\24\26\4\0\1\26\1\0\5\26\24\0"+
    "\1\26\5\0\4\26\1\151\21\26\4\0\1\26\1\0"+
    "\5\26\24\0\1\26\5\0\21\26\1\152\4\26\4\0"+
    "\1\26\1\0\5\26\24\0\1\26\5\0\2\26\1\153"+
    "\23\26\4\0\1\26\1\0\5\26\24\0\1\26\5\0"+
    "\15\26\1\154\10\26\4\0\1\26\1\0\1\26\1\154"+
    "\3\26\24\0\1\26\5\0\23\26\1\155\2\26\4\0"+
    "\1\26\1\0\4\26\1\155\24\0\1\26\5\0\20\26"+
    "\1\156\5\26\4\0\1\26\1\0\2\26\1\156\2\26"+
    "\24\0\1\26\5\0\10\26\1\157\15\26\4\0\1\26"+
    "\1\0\5\26\24\0\1\26\5\0\4\26\1\160\21\26"+
    "\4\0\1\26\1\0\5\26\24\0\1\26\5\0\3\26"+
    "\1\161\22\26\4\0\1\26\1\0\5\26\24\0\1\26"+
    "\5\0\13\26\1\162\12\26\4\0\1\26\1\0\5\26"+
    "\24\0\1\163\5\0\6\163\26\0\1\163\30\0\1\26"+
    "\5\0\12\26\1\164\13\26\4\0\1\26\1\0\5\26"+
    "\24\0\1\26\5\0\22\26\1\165\3\26\4\0\1\26"+
    "\1\0\3\26\1\165\1\26\24\0\1\26\5\0\10\26"+
    "\1\166\15\26\4\0\1\26\1\0\5\26\24\0\1\26"+
    "\5\0\13\26\1\167\12\26\4\0\1\26\1\0\5\26"+
    "\24\0\1\26\5\0\4\26\1\170\21\26\4\0\1\26"+
    "\1\0\5\26\24\0\1\26\5\0\7\26\1\171\16\26"+
    "\4\0\1\26\1\0\5\26\24\0\1\26\5\0\22\26"+
    "\1\172\3\26\4\0\1\26\1\0\3\26\1\172\1\26"+
    "\24\0\1\26\5\0\20\26\1\173\5\26\4\0\1\26"+
    "\1\0\2\26\1\173\2\26\24\0\1\26\5\0\22\26"+
    "\1\174\3\26\4\0\1\26\1\0\3\26\1\174\1\26"+
    "\24\0\1\26\5\0\15\26\1\175\10\26\4\0\1\26"+
    "\1\0\1\26\1\175\3\26\24\0\1\26\5\0\4\26"+
    "\1\176\21\26\4\0\1\26\1\0\5\26\24\0\1\177"+
    "\5\0\6\177\26\0\1\177\30\0\1\26\5\0\15\26"+
    "\1\200\10\26\4\0\1\26\1\0\1\26\1\200\3\26"+
    "\24\0\1\26\5\0\4\26\1\201\21\26\4\0\1\26"+
    "\1\0\5\26\24\0\1\26\5\0\13\26\1\202\12\26"+
    "\4\0\1\26\1\0\5\26\24\0\1\26\5\0\15\26"+
    "\1\203\10\26\4\0\1\26\1\0\1\26\1\203\3\26"+
    "\24\0\1\26\5\0\26\26\4\0\1\204\1\0\5\26"+
    "\24\0\1\26\5\0\6\26\1\205\17\26\4\0\1\26"+
    "\1\0\5\26\24\0\1\57\5\0\6\57\26\0\1\57"+
    "\30\0\1\26\5\0\23\26\1\206\2\26\4\0\1\26"+
    "\1\0\4\26\1\206\24\0\1\26\5\0\15\26\1\207"+
    "\10\26\4\0\1\26\1\0\1\26\1\207\3\26\24\0"+
    "\1\26\5\0\25\26\1\210\4\0\1\26\1\0\5\26"+
    "\24\0\1\26\5\0\4\26\1\211\21\26\4\0\1\26"+
    "\1\0\5\26\24\0\1\26\5\0\10\26\1\212\15\26"+
    "\4\0\1\26\1\0\5\26\24\0\1\26\5\0\22\26"+
    "\1\213\3\26\4\0\1\26\1\0\3\26\1\213\1\26"+
    "\24\0\1\26\5\0\7\26\1\214\16\26\4\0\1\26"+
    "\1\0\5\26\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5546];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\2\11\1\1\3\11"+
    "\2\1\2\11\25\1\1\11\1\1\2\11\1\0\2\11"+
    "\2\0\1\11\1\0\1\1\1\0\3\11\22\1\2\11"+
    "\2\0\23\1\1\0\1\11\20\1\1\0\13\1\1\0"+
    "\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public LinkedList<Errores> listaErrores = new LinkedList<>();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
      yyline = 1;
    yycolumn = 1;
    listaErrores = new LinkedList<>();
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { listaErrores.add(new Errores("LEXICO","El caracter "+
                yytext()+" NO pertenece al lenguaje", yyline, yycolumn));
            }
          // fall through
          case 56: break;
          case 2:
            { 
            }
          // fall through
          case 57: break;
          case 3:
            { return new Symbol(sym.TKNOT, yyline, yycolumn,yytext());
            }
          // fall through
          case 58: break;
          case 4:
            { return new Symbol(sym.MOD, yyline, yycolumn,yytext());
            }
          // fall through
          case 59: break;
          case 5:
            { return new Symbol(sym.PAR1, yyline, yycolumn,yytext());
            }
          // fall through
          case 60: break;
          case 6:
            { return new Symbol(sym.PAR2, yyline, yycolumn,yytext());
            }
          // fall through
          case 61: break;
          case 7:
            { return new Symbol(sym.MULT, yyline, yycolumn,yytext());
            }
          // fall through
          case 62: break;
          case 8:
            { return new Symbol(sym.MAS, yyline, yycolumn,yytext());
            }
          // fall through
          case 63: break;
          case 9:
            { return new Symbol(sym.COMA, yyline, yycolumn,yytext());
            }
          // fall through
          case 64: break;
          case 10:
            { return new Symbol(sym.MENOS, yyline, yycolumn,yytext());
            }
          // fall through
          case 65: break;
          case 11:
            { return new Symbol(sym.DIV, yyline, yycolumn,yytext());
            }
          // fall through
          case 66: break;
          case 12:
            { return new Symbol(sym.ENTERO, yyline, yycolumn,yytext());
            }
          // fall through
          case 67: break;
          case 13:
            { return new Symbol(sym.DOSPUNTOS, yyline, yycolumn,yytext());
            }
          // fall through
          case 68: break;
          case 14:
            { return new Symbol(sym.FINCADENA, yyline, yycolumn,yytext());
            }
          // fall through
          case 69: break;
          case 15:
            { return new Symbol(sym.MENOR, yyline, yycolumn,yytext());
            }
          // fall through
          case 70: break;
          case 16:
            { return new Symbol(sym.IGUAL, yyline, yycolumn,yytext());
            }
          // fall through
          case 71: break;
          case 17:
            { return new Symbol(sym.MAYOR, yyline, yycolumn,yytext());
            }
          // fall through
          case 72: break;
          case 18:
            { return new Symbol(sym.ID, yyline, yycolumn,yytext());
            }
          // fall through
          case 73: break;
          case 19:
            { return new Symbol(sym.CORCHETE1, yyline, yycolumn,yytext());
            }
          // fall through
          case 74: break;
          case 20:
            { return new Symbol(sym.CORCHETE2, yyline, yycolumn,yytext());
            }
          // fall through
          case 75: break;
          case 21:
            { return new Symbol(sym.TKXOR, yyline, yycolumn,yytext());
            }
          // fall through
          case 76: break;
          case 22:
            { return new Symbol(sym.GUIONBAJO, yyline, yycolumn,yytext());
            }
          // fall through
          case 77: break;
          case 23:
            { return new Symbol(sym.LLAVE1, yyline, yycolumn,yytext());
            }
          // fall through
          case 78: break;
          case 24:
            { return new Symbol(sym.LLAVE2, yyline, yycolumn,yytext());
            }
          // fall through
          case 79: break;
          case 25:
            { return new Symbol(sym.DIFERENCIA, yyline, yycolumn,yytext());
            }
          // fall through
          case 80: break;
          case 26:
            { String cadena = yytext();
                            cadena = cadena.substring(1, cadena.length()-1);
                            int find = -1;
                            
                            find = cadena.indexOf("\\n"); 
                            if (find != -1) {
                                cadena = cadena.replace("\\n", "\n");
                            }

                            find = cadena.indexOf("\\t"); 
                            if (find != -1) {
                                cadena = cadena.replace("\\t", "\t");
                            }

                            find = cadena.indexOf("\\r"); 
                            if (find != -1) {
                                cadena = cadena.replace("\\r", "\r");
                            }

                            find = cadena.indexOf("\\f"); 
                            if (find != -1) {
                                cadena = cadena.replace("\\f", "\f");
                            }
                            
                            return new Symbol(sym.CADENA, yyline, yycolumn,cadena);
            }
          // fall through
          case 81: break;
          case 27:
            { return new Symbol(sym.TKAND, yyline, yycolumn,yytext());
            }
          // fall through
          case 82: break;
          case 28:
            { return new Symbol(sym.POTENCIA, yyline, yycolumn,yytext());
            }
          // fall through
          case 83: break;
          case 29:
            { return new Symbol(sym.MENORIGUAL, yyline, yycolumn,yytext());
            }
          // fall through
          case 84: break;
          case 30:
            { return new Symbol(sym.IGUALACION, yyline, yycolumn,yytext());
            }
          // fall through
          case 85: break;
          case 31:
            { return new Symbol(sym.MAYORIGUAL, yyline, yycolumn,yytext());
            }
          // fall through
          case 86: break;
          case 32:
            { return new Symbol(sym.DO, yyline, yycolumn,yytext());
            }
          // fall through
          case 87: break;
          case 33:
            { return new Symbol(sym.IF, yyline, yycolumn,yytext());
            }
          // fall through
          case 88: break;
          case 34:
            { return new Symbol(sym.TKOR, yyline, yycolumn,yytext());
            }
          // fall through
          case 89: break;
          case 35:
            { String caracter = yytext();
                            caracter = caracter.substring(1, caracter.length()-1);
                            if (caracter.equals("\\n")) {
                                caracter = "\n";
                            }
                            if (caracter.equals("\\r")) {
                                caracter = "\r";
                            }
                            if (caracter.equals("\\t")) {
                                caracter = "\t";
                            }
                            if (caracter.equals("\\f")) {
                                caracter = "\f";
                            }
                            return new Symbol(sym.CARACTER, yyline, yycolumn, caracter);
            }
          // fall through
          case 90: break;
          case 36:
            { return new Symbol(sym.DECIMAL, yyline, yycolumn,yytext());
            }
          // fall through
          case 91: break;
          case 37:
            { return new Symbol(sym.FOR, yyline, yycolumn,yytext());
            }
          // fall through
          case 92: break;
          case 38:
            { return new Symbol(sym.TKINT, yyline, yycolumn,yytext());
            }
          // fall through
          case 93: break;
          case 39:
            { return new Symbol(sym.VAR, yyline, yycolumn,yytext());
            }
          // fall through
          case 94: break;
          case 40:
            { return new Symbol(sym.TKBOOL, yyline, yycolumn,yytext());
            }
          // fall through
          case 95: break;
          case 41:
            { return new Symbol(sym.TKCHAR, yyline, yycolumn,yytext());
            }
          // fall through
          case 96: break;
          case 42:
            { return new Symbol(sym.ELSE, yyline, yycolumn,yytext());
            }
          // fall through
          case 97: break;
          case 43:
            { return new Symbol(sym.VERDAD, yyline, yycolumn,yytext());
            }
          // fall through
          case 98: break;
          case 44:
            { return new Symbol(sym.VOID, yyline, yycolumn,yytext());
            }
          // fall through
          case 99: break;
          case 45:
            { return new Symbol(sym.BREAK, yyline, yycolumn,yytext());
            }
          // fall through
          case 100: break;
          case 46:
            { return new Symbol(sym.CONST, yyline, yycolumn,yytext());
            }
          // fall through
          case 101: break;
          case 47:
            { return new Symbol(sym.FALSO, yyline, yycolumn,yytext());
            }
          // fall through
          case 102: break;
          case 48:
            { return new Symbol(sym.MATCH, yyline, yycolumn,yytext());
            }
          // fall through
          case 103: break;
          case 49:
            { return new Symbol(sym.WHILE, yyline, yycolumn,yytext());
            }
          // fall through
          case 104: break;
          case 50:
            { return new Symbol(sym.TKDOUBLE, yyline, yycolumn,yytext());
            }
          // fall through
          case 105: break;
          case 51:
            { return new Symbol(sym.RETURN, yyline, yycolumn,yytext());
            }
          // fall through
          case 106: break;
          case 52:
            { return new Symbol(sym.TKSTRING, yyline, yycolumn,yytext());
            }
          // fall through
          case 107: break;
          case 53:
            { return new Symbol(sym.PRINTLN, yyline, yycolumn,yytext());
            }
          // fall through
          case 108: break;
          case 54:
            { return new Symbol(sym.CONTINUE, yyline, yycolumn,yytext());
            }
          // fall through
          case 109: break;
          case 55:
            { return new Symbol(sym.START_WITH, yyline, yycolumn,yytext());
            }
          // fall through
          case 110: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
