
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TKINT = 33;
  public static final int PAR2 = 12;
  public static final int DOSPUNTOS = 10;
  public static final int PAR1 = 11;
  public static final int DIFERENCIA = 23;
  public static final int MULT = 16;
  public static final int CONST = 37;
  public static final int IGUALACION = 22;
  public static final int TKNOT = 28;
  public static final int TKAND = 30;
  public static final int ENTERO = 3;
  public static final int TKOR = 29;
  public static final int TKBOOL = 36;
  public static final int PRINTLN = 9;
  public static final int FINCADENA = 8;
  public static final int MENORIGUAL = 24;
  public static final int IGUAL = 7;
  public static final int CARACTER = 5;
  public static final int VERDAD = 20;
  public static final int DIV = 17;
  public static final int UMENOS = 19;
  public static final int ID = 6;
  public static final int MAYORIGUAL = 26;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int error = 1;
  public static final int CADENA = 2;
  public static final int MENOS = 14;
  public static final int MENOR = 25;
  public static final int MOD = 18;
  public static final int TKSTRING = 35;
  public static final int MAYOR = 27;
  public static final int POTENCIA = 15;
  public static final int FALSO = 21;
  public static final int TKCHAR = 34;
  public static final int VAR = 38;
  public static final int TKXOR = 31;
  public static final int TKDOUBLE = 32;
  public static final int MAS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "CARACTER",
  "ID",
  "IGUAL",
  "FINCADENA",
  "PRINTLN",
  "DOSPUNTOS",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "POTENCIA",
  "MULT",
  "DIV",
  "MOD",
  "UMENOS",
  "VERDAD",
  "FALSO",
  "IGUALACION",
  "DIFERENCIA",
  "MENORIGUAL",
  "MENOR",
  "MAYORIGUAL",
  "MAYOR",
  "TKNOT",
  "TKOR",
  "TKAND",
  "TKXOR",
  "TKDOUBLE",
  "TKINT",
  "TKCHAR",
  "TKSTRING",
  "TKBOOL",
  "CONST",
  "VAR"
  };
}

