
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TKINT = 37;
  public static final int PAR2 = 14;
  public static final int DOSPUNTOS = 10;
  public static final int PAR1 = 13;
  public static final int DIFERENCIA = 27;
  public static final int MULT = 18;
  public static final int CONST = 41;
  public static final int GUIONBAJO = 22;
  public static final int IGUALACION = 26;
  public static final int TKNOT = 32;
  public static final int TKAND = 34;
  public static final int LLAVE2 = 12;
  public static final int LLAVE1 = 11;
  public static final int ENTERO = 3;
  public static final int TKOR = 33;
  public static final int CONTINUE = 51;
  public static final int TKBOOL = 40;
  public static final int PRINTLN = 9;
  public static final int FOR = 47;
  public static final int MATCH = 45;
  public static final int FINCADENA = 8;
  public static final int MENORIGUAL = 28;
  public static final int IGUAL = 7;
  public static final int CARACTER = 5;
  public static final int VERDAD = 24;
  public static final int DIV = 19;
  public static final int IF = 43;
  public static final int UMENOS = 21;
  public static final int ID = 6;
  public static final int MAYORIGUAL = 30;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int error = 1;
  public static final int COMA = 23;
  public static final int CADENA = 2;
  public static final int MENOS = 16;
  public static final int MENOR = 29;
  public static final int MOD = 20;
  public static final int BREAK = 50;
  public static final int VOID = 49;
  public static final int TKSTRING = 39;
  public static final int MAYOR = 31;
  public static final int POTENCIA = 17;
  public static final int ELSE = 44;
  public static final int START_WITH = 52;
  public static final int WHILE = 46;
  public static final int FALSO = 25;
  public static final int TKCHAR = 38;
  public static final int VAR = 42;
  public static final int TKDOUBLE = 36;
  public static final int TKXOR = 35;
  public static final int DO = 48;
  public static final int MAS = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "CARACTER",
  "ID",
  "IGUAL",
  "FINCADENA",
  "PRINTLN",
  "DOSPUNTOS",
  "LLAVE1",
  "LLAVE2",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "POTENCIA",
  "MULT",
  "DIV",
  "MOD",
  "UMENOS",
  "GUIONBAJO",
  "COMA",
  "VERDAD",
  "FALSO",
  "IGUALACION",
  "DIFERENCIA",
  "MENORIGUAL",
  "MENOR",
  "MAYORIGUAL",
  "MAYOR",
  "TKNOT",
  "TKOR",
  "TKAND",
  "TKXOR",
  "TKDOUBLE",
  "TKINT",
  "TKCHAR",
  "TKSTRING",
  "TKBOOL",
  "CONST",
  "VAR",
  "IF",
  "ELSE",
  "MATCH",
  "WHILE",
  "FOR",
  "DO",
  "VOID",
  "BREAK",
  "CONTINUE",
  "START_WITH"
  };
}

